name: ARK-5
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang automake autoconf zlib-dev python3 zip

      - name: Cloning and Building lastest pspsdk
        run: | 
          git clone https://github.com/pspdev/pspsdk

      - name: Bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: Checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive

      - name: Update psp-cfw-sdk
        run: psp-pacman -Syyu --noconfirm && psp-pacman -Rsn ark-dev-sdk libpspexploit --noconfirm && psp-pacman -S psp-cfw-sdk --noconfirm

      - name: Upgrade psp-cfw-sdk via Github
        run: |
          git clone https://github.com/pspdev/psp-cfw-sdk.git
          cd psp-cfw-sdk
          make
          make install
          cd ..

      - name: Build
        run:  make clean && make 

      - name: Compress
        run: |
          cd dist
          zip -r ../ARK-5.zip .
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ark-release
          path: ARK-5.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ark-release
          path: .
      - name:
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: ARK-5 pre-release
          prerelease: true
          files: ARK-5.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    
