name: ARK-5
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang automake autoconf zlib-dev python3

      - name: Cloning and Building lastest pspsdk
        run: | 
          git clone https://github.com/pspdev/pspsdk

      - name: Bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: Checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive

      - name: Update psp-cfw-sdk
        run: psp-pacman -Syyu --noconfirm && psp-pacman -Rsn ark-dev-sdk libpspexploit --noconfirm && psp-pacman -S psp-cfw-sdk --noconfirm

      - name: Build
        run:  make clean && make 

      - name: Compress
        run: |
          cd dist
          zip -r ARK-5.zip .
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: dist/*.zip
      - name:
        uses: softprops/actions-gh-release@v2
        with:
          prerelease: true
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    
